[tool.poetry]
name = "pyobs-core"
version = "0.14.0"
description = "robotic telescope software"
authors = ["Tim-Oliver Husser <thusser@uni-goettingen.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
scipy = "^1.7.2"
pandas = "^1.1.5"
astropy = "^4.2"
astroplan =  "^0.7"
numpy = "^1.21.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
