name: Publish package to PyPI
on:
  push:
    tags:
    - 'v*'
jobs:
  build-n-publish:
    name: Build and publish package to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.9
        with:
          pypi_token: ${{ secrets.pypi_password }}
